/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RDBASE_H_RPCGEN
#define _RDBASE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXWORD 50
#define DICTSIZ 100
#define MAXRESULT 10
#define MAXSUCHERG 100

struct upd {
	char *upd_old;
	char *upd_new;
};
typedef struct upd upd;

struct oneword {
	char *word;
};
typedef struct oneword oneword;

struct manywords {
	struct {
		u_int words_len;
		oneword *words_val;
	} words;
};
typedef struct manywords manywords;

#define RDBASEPROG 0x30090949
#define RDBASEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INITW 1
extern  int * initw_1(void *, CLIENT *);
extern  int * initw_1_svc(void *, struct svc_req *);
#define INSERTW 2
extern  int * insertw_1(char **, CLIENT *);
extern  int * insertw_1_svc(char **, struct svc_req *);
#define DELETEW 3
extern  int * deletew_1(char **, CLIENT *);
extern  int * deletew_1_svc(char **, struct svc_req *);
#define LOOKUPW 4
extern  int * lookupw_1(char **, CLIENT *);
extern  int * lookupw_1_svc(char **, struct svc_req *);
#define UPDATEW 5
extern  int * updatew_1(upd *, CLIENT *);
extern  int * updatew_1_svc(upd *, struct svc_req *);
#define COUNTW 6
extern  int * countw_1(void *, CLIENT *);
extern  int * countw_1_svc(void *, struct svc_req *);
#define SELECTW 7
extern  char ** selectw_1(void *, CLIENT *);
extern  char ** selectw_1_svc(void *, struct svc_req *);
#define SELECT2W 8
extern  manywords * select2w_1(void *, CLIENT *);
extern  manywords * select2w_1_svc(void *, struct svc_req *);
extern int rdbaseprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INITW 1
extern  int * initw_1();
extern  int * initw_1_svc();
#define INSERTW 2
extern  int * insertw_1();
extern  int * insertw_1_svc();
#define DELETEW 3
extern  int * deletew_1();
extern  int * deletew_1_svc();
#define LOOKUPW 4
extern  int * lookupw_1();
extern  int * lookupw_1_svc();
#define UPDATEW 5
extern  int * updatew_1();
extern  int * updatew_1_svc();
#define COUNTW 6
extern  int * countw_1();
extern  int * countw_1_svc();
#define SELECTW 7
extern  char ** selectw_1();
extern  char ** selectw_1_svc();
#define SELECT2W 8
extern  manywords * select2w_1();
extern  manywords * select2w_1_svc();
extern int rdbaseprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_upd (XDR *, upd*);
extern  bool_t xdr_oneword (XDR *, oneword*);
extern  bool_t xdr_manywords (XDR *, manywords*);

#else /* K&R C */
extern bool_t xdr_upd ();
extern bool_t xdr_oneword ();
extern bool_t xdr_manywords ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RDBASE_H_RPCGEN */
